services:
  nginx:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./snippets:/etc/nginx/snippets:ro
      - ./templates:/etc/nginx/templates:ro
      - ./logs:/var/log/nginx
    environment:
      API_PORT: ${API_PORT}
    healthcheck:
      test: "curl --fail -s --header 'Host: localhost' http://127.0.0.1/health || exit 1"
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s
    ports:
      - 127.0.0.1:${WEB_PORT}:80
    networks:
      - simple-full-stack
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  simple-full-stack:
    external: true
